default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DB_POOL') { 15 } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DB_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>
  timeout: 10000

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'book_api_development' } %>

test:
  <<: *default
  database: book_api_test

staging:
  <<: *default

production:
  <<: *default
